name: sonarscanner_dart
version: 0.1.0
description: >
  The SonarScanner for Dart provides an easy way to start SonarQube analysis of a dart project.
homepage: https://github.com/meniga/sonarscanner-for-dart

environment:
  sdk: ">=2.5.0 <3.0.0"

executables:
  sonarscanner_dart:

dependencies:
  args: ^1.5.2
  equatable: ^1.1.1
  logging: ^0.11.4
  meta: ^1.1.7
  moronepo:
    git:
      url: git@github.com:meniga/moronepo.git
      ref: prepare-release-0.1.2
  path: ^1.6.4
  quiver: ^2.0.0

dev_dependencies:
  matcher: ^0.12.5
  pedantic: ^1.8.0+1
  test: ^1.6.3
  test_coverage: ^0.4.1
